# Generated by Django 5.0.6 on 2024-08-07 10:02

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('narxi', models.IntegerField()),
                ('rasm', models.ImageField(upload_to='photo')),
                ('holati', models.BooleanField(default=False)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('rand', models.CharField(default=main.models.uniqid, max_length=32, unique=True)),
            ],
        ),
    ]
