# Generated by Django 5.0.6 on 2024-08-07 10:06

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='rand',
            field=models.CharField(auto_created=True, default=main.models.uniqid, max_length=32, unique=True),
        ),
    ]
