# Generated by Django 5.0.6 on 2024-08-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_food_rand'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFoodList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('nomi', models.CharField(max_length=255)),
                ('narxi', models.IntegerField()),
                ('rasm', models.TextField()),
                ('soni', models.IntegerField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
