# Generated by Django 5.0.6 on 2024-08-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userfoodlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.IntegerField(verbose_name='Admin ID')),
            ],
            options={
                'verbose_name': 'Admin ID',
                'verbose_name_plural': 'Admin ID',
            },
        ),
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, verbose_name='Karta raqami')),
                ('qr_kod', models.ImageField(upload_to='qr_code', verbose_name='QR kod rasmi')),
            ],
            options={
                'verbose_name': "Karta ma'lumotlari",
                'verbose_name_plural': "Karta ma'lumotlari",
            },
        ),
    ]
